### ISSUE TITLE
Final presentation and slides

### ISSUE THREAD

**Issue by aleks96n** [aleks96n/Electric-Vehicle-Charging-Predictor#12]
It should include all the techniques used, some graphs and results, as well as UI/API.
Also, 30% is based on the quality of the presentation. My guess is that it means that the presentation doesn't need to be pretty, but the presenter must know what they are talking about and explain techniques in an interesting way.

1. Title and project owner (5 seconds)
2. What is the goal of the project (problem statement, NO, NOT DIFFICULTIES IN THE PROJECT) (30 seconds)
3. Techniques used and their accuracy (2 minutes)
5. UI per 24-hour explanation (part of the task) (30-60 seconds)
4. What lessons did we learn (you may comment on this issue, describing what you learned)

**Comment by HandyKurniawan** [comment]
Done!
